---
title: Lancaster DSA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Chapter of the Democratic Socialists of America covering Lancaster and
  York counties in Pennsylvania.
baseurl: ''
url: https://lancdsa.org
theme: minima
plugins:
- jekyll-feed
exclude:
- README.md
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
